language: bash
services: docker

env:
  - VARIANT=full
  - VARIANT=slim

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image="google-gcloud-sdk:${VARIANT}"

script:
  - cd $VARIANT
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:i